version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend API
      - "3000:3000"  # Frontend
    depends_on:
      - ollama
    volumes:
      - ./logs:/app/logs
      - ./backend/api_keys.env:/app/backend/api_keys.env
    networks:
      - courser-network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    command: serve
    networks:
      - courser-network

volumes:
  ollama-data:

networks:
  courser-network:
    driver: bridge
