version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend API
      - "3001:3000"  # Frontend (adjusted to avoid port conflict)
    volumes:
      - ./logs:/app/logs
      - ./backend/api_keys.env:/app/backend/api_keys.env
    networks:
      - courser-network

volumes:
  app-data:

networks:
  courser-network:
    driver: bridge